const Actions = {
    ADD_TITULAR: 'ADD_TITULAR',
    ADD_SUBSTITUTE: 'ADD_SUBSTITUTE',
    REMOVE_TITULAR: 'REMOVE_TITULAR',
    REMOVE_SUBSTITUTE: 'REMOVE_SUBSTITUTE',
    POPULATE_PLAYERS: 'POPULATE_PLAYERS'
}

export default Actions